version: 2.2.{build}
configuration: Release
pull_requests:
  do_not_increment_build_number: true
image:
- Visual Studio 2017
- Ubuntu
dotnet_csproj:
  patch: true
  file: '**\ChangeTracking.csproj'
  version: '{version}'
  package_version: '{version}'
before_build:
- ps: dotnet restore Source\ChangeTracking.sln
build:
  project: Source\ChangeTracking.sln
  publish_nuget: true
  verbosity: minimal
test_script:
- ps: dotnet test Source\ChangeTracking.Tests\ChangeTracking.Tests.csproj
for:
-
  matrix:
    only:
      - image: Ubuntu
  build_script:
  - ps: dotnet build Source\ChangeTracking\ChangeTracking.csproj --framework netstandard2.0
  test_script:
  - ps: dotnet test Source\ChangeTracking.Tests\ChangeTracking.Tests.csproj --framework netcoreapp2.0
